import Foundation

// Swift port of dynamic-map/src/utils/pacingAlgorithm.ts.
// Kept behaviorally identical (same constants, same formulas) so a session
// generated by the watch matches what the web app would produce.
enum PacingAlgorithm {
    /// Island interior bounds (percentages of the map viewBox) that nodes may scatter within.
    static let mapBounds = (minX: 14.0, maxX: 86.0, minY: 20.0, maxY: 80.0)

    private static let minNodeDistance = 9.0
    private static let maxPlacementAttempts = 24

    private static let spacingMinutesByRate: [RateOfChange: Double] = [
        .low: 9, .medium: 6, .high: 4,
    ]

    private static let oscillationPeriodByRate: [RateOfChange: Double] = [
        .low: 5, .medium: 4, .high: 3,
    ]

    /// Fraction of the half-range (max - min) / 2 that the oscillation swings by.
    private static let amplitudeFractionByRate: [RateOfChange: Double] = [
        .low: 0.4, .medium: 0.7, .high: 1,
    ]

    private static func distance(_ a: MapCoordinates, _ b: MapCoordinates) -> Double {
        let dx = a.x - b.x
        let dy = a.y - b.y
        return (dx * dx + dy * dy).squareRoot()
    }

    static func randomCoordinate(existing: [MapCoordinates]) -> MapCoordinates {
        var candidate = MapCoordinates(x: 0, y: 0)
        for _ in 0..<maxPlacementAttempts {
            candidate = MapCoordinates(
                x: mapBounds.minX + Double.random(in: 0...1) * (mapBounds.maxX - mapBounds.minX),
                y: mapBounds.minY + Double.random(in: 0...1) * (mapBounds.maxY - mapBounds.minY)
            )
            let tooClose = existing.contains { distance($0, candidate) < minNodeDistance }
            if !tooClose { return candidate }
        }
        return candidate
    }

    static func clampLevel(_ level: Double, minLevel: CognitiveLevel, maxLevel: CognitiveLevel) -> CognitiveLevel {
        Int(min(Double(maxLevel), max(Double(minLevel), level.rounded())))
    }

    private static func baseLevelForSeason(
        _ entrySeason: Season, minLevel: CognitiveLevel, maxLevel: CognitiveLevel
    ) -> Double {
        let midpoint = Double(minLevel + maxLevel) / 2
        switch entrySeason {
        case .battle:
            return Double(maxLevel - 1)
        case .exhaustionRecovery:
            return Double(minLevel)
        default:
            return midpoint
        }
    }

    /// Builds the cognitive-level sequence for a path, ranging between the min and max load.
    static func buildLevelSequence(
        count: Int,
        minLevel: CognitiveLevel,
        maxLevel: CognitiveLevel,
        entrySeason: Season,
        rateOfChange: RateOfChange,
        cyclePattern: CyclePattern
    ) -> [CognitiveLevel] {
        let period = oscillationPeriodByRate[rateOfChange] ?? 4

        if cyclePattern == .ramp {
            return (0..<count).map { i in
                let phase = period <= 1 ? 0 : Double(i % Int(period)) / (period - 1)
                return clampLevel(
                    Double(minLevel) + phase * Double(maxLevel - minLevel),
                    minLevel: minLevel, maxLevel: maxLevel
                )
            }
        }

        let base = baseLevelForSeason(entrySeason, minLevel: minLevel, maxLevel: maxLevel)
        let halfRange = max(Double(maxLevel - minLevel) / 2, 0.5)
        let amplitude = halfRange * (amplitudeFractionByRate[rateOfChange] ?? 0.7)

        return (0..<count).map { i in
            let wave = base + amplitude * sin((2 * Double.pi * Double(i)) / period)
            return clampLevel(wave, minLevel: minLevel, maxLevel: maxLevel)
        }
    }

    static func kindForLevel(
        index: Int,
        count: Int,
        level: CognitiveLevel,
        minLevel: CognitiveLevel,
        maxLevel: CognitiveLevel,
        entrySeason: Season
    ) -> PitstopKind {
        if index == 0 { return .start }
        if index == count - 1 { return .end }
        if entrySeason == .exhaustionRecovery && level <= minLevel { return .recovery }
        if level >= maxLevel { return .peak }
        return .work
    }

    private static let labelByKind: [PitstopKind: String] = [
        .start: "Start", .end: "End", .work: "Work", .peak: "Peak",
        .recovery: "Recovery", .grounding: "Grounding", .stranding: "Stranded",
    ]

    static func labelFor(_ kind: PitstopKind, _ level: CognitiveLevel) -> String {
        let base = labelByKind[kind] ?? ""
        if kind == .start || kind == .end { return base }
        return "\(base) · L\(level)"
    }

    /// Number of pitstops (including start/end) for a given duration and rate of change.
    static func pitstopCount(forDurationMinutes durationMinutes: Double, rateOfChange: RateOfChange) -> Int {
        let spacing = spacingMinutesByRate[rateOfChange] ?? 6
        let count = Int((durationMinutes / spacing).rounded()) + 1
        return min(16, max(4, count))
    }

    /// How far a segment's weight swings from the average (1) at the extremes of a negative/positive split.
    private static let splitSkew = 0.6

    private static func segmentWeights(segments: Int, splitType: SplitType) -> [Double] {
        if segments <= 1 || splitType == .even {
            return Array(repeating: 1.0, count: segments)
        }
        return (0..<segments).map { i in
            let t = Double(i) / Double(segments - 1) // 0 (first segment) -> 1 (last segment)
            return splitType == .negative
                ? 1 + splitSkew - t * 2 * splitSkew // long segments first, shrinking
                : 1 - splitSkew + t * 2 * splitSkew // short segments first, growing
        }
    }

    /// Lays out scheduledTime offsets (ms) across [startMs, startMs + durationMs], with mild
    /// organic jitter, shaped by splitType, while preserving monotonic ordering, a minimum
    /// gap, and the exact total duration.
    static func layoutSchedule(count: Int, startMs: Double, durationMs: Double, splitType: SplitType) -> [Double] {
        if count == 1 { return [startMs] }
        let segments = count - 1
        let weights = segmentWeights(segments: segments, splitType: splitType)
        let rawDurations = weights.map { ($0 / Double(segments)) * durationMs }
        let minGap = (rawDurations.min() ?? 0) * 0.3

        var times: [Double] = [startMs]
        for i in 0..<segments {
            let isLastSegment = i == segments - 1
            let jitter = isLastSegment ? 0 : (Double.random(in: 0...1) - 0.5) * rawDurations[i] * 0.25
            let prev = times[times.count - 1]
            let candidate = prev + rawDurations[i] + jitter
            times.append(max(candidate, prev + minGap))
        }
        // Clamp the final point back to the exact end so the total duration is preserved.
        times[times.count - 1] = startMs + durationMs
        return times
    }

    static func generateInitialPath(task: WatchTask, preferences: UserPreferences) -> PacingPath {
        let totalDurationMs = Double(task.durationMinutes) * 60_000
        let count = pitstopCount(forDurationMinutes: Double(task.durationMinutes), rateOfChange: task.rateOfChange)
        let minLevel = min(task.minCognitiveLevel, task.cognitiveLimit)
        let maxLevel = task.cognitiveLimit
        let levels = buildLevelSequence(
            count: count, minLevel: minLevel, maxLevel: maxLevel,
            entrySeason: task.entrySeason, rateOfChange: task.rateOfChange,
            cyclePattern: preferences.cyclePattern
        )
        let schedule = layoutSchedule(
            count: count, startMs: 0, durationMs: totalDurationMs, splitType: preferences.splitType
        )

        var pitstops: [Pitstop] = []
        for i in 0..<count {
            let level = levels[i]
            let kind = kindForLevel(
                index: i, count: count, level: level,
                minLevel: minLevel, maxLevel: maxLevel, entrySeason: task.entrySeason
            )
            let coords = randomCoordinate(existing: pitstops.map(\.mapCoordinates))
            pitstops.append(Pitstop(
                id: generateId("pitstop"),
                label: labelFor(kind, level),
                level: level,
                season: task.entrySeason,
                kind: kind,
                scheduledTime: schedule[i],
                realTimeTrigger: i == 0 ? Date().timeIntervalSince1970 * 1000 : nil,
                mapCoordinates: coords
            ))
        }

        return PacingPath(pitstops: pitstops, totalDurationMs: totalDurationMs)
    }
}
